### ISSUE TITLE
Roadmap for 0.16.0

### ISSUE THREAD

**Issue by mfherbst** [adc-connect/adcc#113]
- [x] Merge #105
- [x] Tag 0.15.6 and check the deployment pipeline works
- [x] libxm support #118
- [x] py-side `OneParticleOperator` #119 
- [x] Publish libtensorlight 3.0.0
- [x] Update libtensorlight here (done in #118)
- [x] PE-ADC dynamic reaction field (#123)
- [x] Let the steam cool down and test in production for some time (maybe until Feb 2021?)
- [x] Remove deprecated features (#183)
- [x] Solver convergence issues (#175)
- [x] New integrals/operators (#169)
- [x] Publish 0.16.0

@maxscheurer Thoughts?

**Comment by maxscheurer** [comment]
Nice, I will add stuff here 👍🏻 We can also use a v0.16.0 milestone in the following PRs to have a decent changelog.

**Comment by mfherbst** [comment]
I'm also wondering whether we should start thinking towards 1.0.0 actually. That requires some thought because of the implied  stabilisation of interfaces (we should not have breaking changes in the interface after that). But I think at least the most important user-facing aspects are reasonably converged by now that major restructuring is probably not needed any more.
